import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

/**
 * Material 3 (Material You) color scheme, seeded from the brand indigo
 * #4F46E5 — tonal palettes approximated per the M3 spec.
 * Single source of truth: tailwind.config.js mirrors these tokens.
 */
export const m3 = {
  light: {
    primary: '#4F46E5',
    onPrimary: '#FFFFFF',
    primaryContainer: '#E2DFFF',
    onPrimaryContainer: '#0E0664',
    secondary: '#5D5C72',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E2E0F9',
    onSecondaryContainer: '#1A1A2C',
    tertiary: '#006A60',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#74F8E5',
    onTertiaryContainer: '#00201C',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    surface: '#FCF8FF',
    onSurface: '#1B1B21',
    surfaceVariant: '#E4E1EC',
    onSurfaceVariant: '#46464F',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F6F2FA',
    surfaceContainer: '#F0ECF4',
    surfaceContainerHigh: '#EAE7EF',
    surfaceContainerHighest: '#E4E1E9',
    outline: '#777680',
    outlineVariant: '#C7C5D0',
    inverseSurface: '#303036',
    inverseOnSurface: '#F3EFF7',
    inversePrimary: '#BFC2FF',
    // Custom semantic (not in core M3, used for finance states)
    success: '#146C2E',
    successContainer: '#A9F5B6',
    onSuccessContainer: '#002106',
    warning: '#785900',
    warningContainer: '#FFDF9E',
    onWarningContainer: '#261A00',
  },
  dark: {
    primary: '#BFC2FF',
    onPrimary: '#1E1D95',
    primaryContainer: '#3730A3',
    onPrimaryContainer: '#E2DFFF',
    secondary: '#C6C4DD',
    onSecondary: '#2F2E42',
    secondaryContainer: '#454459',
    onSecondaryContainer: '#E2E0F9',
    tertiary: '#54DBC9',
    onTertiary: '#003731',
    tertiaryContainer: '#005048',
    onTertiaryContainer: '#74F8E5',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    surface: '#131318',
    onSurface: '#E4E1E9',
    surfaceVariant: '#46464F',
    onSurfaceVariant: '#C7C5D0',
    surfaceContainerLowest: '#0E0E13',
    surfaceContainerLow: '#1B1B21',
    surfaceContainer: '#1F1F25',
    surfaceContainerHigh: '#2A2A30',
    surfaceContainerHighest: '#35343B',
    outline: '#918F9A',
    outlineVariant: '#46464F',
    inverseSurface: '#E4E1E9',
    inverseOnSurface: '#303036',
    inversePrimary: '#4F46E5',
    success: '#8EDD9C',
    successContainer: '#005321',
    onSuccessContainer: '#A9F5B6',
    warning: '#FABD00',
    warningContainer: '#5B4300',
    onWarningContainer: '#FFDF9E',
  },
} as const;

export type M3Scheme = { [K in keyof typeof m3.light]: string };

export function getScheme(dark: boolean): M3Scheme {
  return (dark ? m3.dark : m3.light) as M3Scheme;
}

/** React Native Paper MD3 themes wired to the same palette. */
export const paperLightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: m3.light.primary,
    onPrimary: m3.light.onPrimary,
    primaryContainer: m3.light.primaryContainer,
    onPrimaryContainer: m3.light.onPrimaryContainer,
    secondary: m3.light.secondary,
    secondaryContainer: m3.light.secondaryContainer,
    onSecondaryContainer: m3.light.onSecondaryContainer,
    tertiary: m3.light.tertiary,
    tertiaryContainer: m3.light.tertiaryContainer,
    error: m3.light.error,
    errorContainer: m3.light.errorContainer,
    onErrorContainer: m3.light.onErrorContainer,
    background: m3.light.surface,
    surface: m3.light.surface,
    surfaceVariant: m3.light.surfaceVariant,
    onSurface: m3.light.onSurface,
    onSurfaceVariant: m3.light.onSurfaceVariant,
    outline: m3.light.outline,
    outlineVariant: m3.light.outlineVariant,
    inverseSurface: m3.light.inverseSurface,
    inverseOnSurface: m3.light.inverseOnSurface,
    inversePrimary: m3.light.inversePrimary,
  },
};

export const paperDarkTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: m3.dark.primary,
    onPrimary: m3.dark.onPrimary,
    primaryContainer: m3.dark.primaryContainer,
    onPrimaryContainer: m3.dark.onPrimaryContainer,
    secondary: m3.dark.secondary,
    secondaryContainer: m3.dark.secondaryContainer,
    onSecondaryContainer: m3.dark.onSecondaryContainer,
    tertiary: m3.dark.tertiary,
    tertiaryContainer: m3.dark.tertiaryContainer,
    error: m3.dark.error,
    errorContainer: m3.dark.errorContainer,
    onErrorContainer: m3.dark.onErrorContainer,
    background: m3.dark.surface,
    surface: m3.dark.surface,
    surfaceVariant: m3.dark.surfaceVariant,
    onSurface: m3.dark.onSurface,
    onSurfaceVariant: m3.dark.onSurfaceVariant,
    outline: m3.dark.outline,
    outlineVariant: m3.dark.outlineVariant,
    inverseSurface: m3.dark.inverseSurface,
    inverseOnSurface: m3.dark.inverseOnSurface,
    inversePrimary: m3.dark.inversePrimary,
  },
};
