import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

/**
 * Material 3 (Material You) color scheme, seeded from a warm brick-rose
 * #984447 — tonal palettes approximated per the M3 spec. Deep-crimson
 * primary, soft rose containers, warm off-white surfaces, and a gold
 * tertiary accent, mirroring the reference design language.
 * Single source of truth: tailwind.config.js mirrors these tokens.
 */
export const m3 = {
  light: {
    primary: '#984447',
    onPrimary: '#FFFFFF',
    primaryContainer: '#FFDAD9',
    onPrimaryContainer: '#3E0A0E',
    secondary: '#775654',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#FFDAD9',
    onSecondaryContainer: '#2C1516',
    tertiary: '#755B2E',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFDEA1',
    onTertiaryContainer: '#271900',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    surface: '#FFF8F7',
    onSurface: '#241918',
    surfaceVariant: '#F4DDDB',
    onSurfaceVariant: '#524342',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#FFF0EF',
    surfaceContainer: '#FDEAE8',
    surfaceContainerHigh: '#F7E4E2',
    surfaceContainerHighest: '#F1DFDD',
    outline: '#857371',
    outlineVariant: '#D8C2C0',
    inverseSurface: '#3A2E2D',
    inverseOnSurface: '#FFEDEB',
    inversePrimary: '#FFB3B2',
    // Custom semantic (not in core M3, used for finance states)
    success: '#146C2E',
    successContainer: '#A9F5B6',
    onSuccessContainer: '#002106',
    warning: '#785900',
    warningContainer: '#FFDF9E',
    onWarningContainer: '#261A00',
  },
  dark: {
    primary: '#FFB3B2',
    onPrimary: '#571D22',
    primaryContainer: '#743337',
    onPrimaryContainer: '#FFDAD9',
    secondary: '#E7BDBA',
    onSecondary: '#442927',
    secondaryContainer: '#5D3F3D',
    onSecondaryContainer: '#FFDAD9',
    tertiary: '#E5C28C',
    onTertiary: '#402D04',
    tertiaryContainer: '#5A4319',
    onTertiaryContainer: '#FFDEA1',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    surface: '#1A1110',
    onSurface: '#F1DFDD',
    surfaceVariant: '#524342',
    onSurfaceVariant: '#D8C2C0',
    surfaceContainerLowest: '#140C0B',
    surfaceContainerLow: '#241918',
    surfaceContainer: '#281D1C',
    surfaceContainerHigh: '#332826',
    surfaceContainerHighest: '#3E3231',
    outline: '#A08C8A',
    outlineVariant: '#524342',
    inverseSurface: '#F1DFDD',
    inverseOnSurface: '#3A2E2D',
    inversePrimary: '#984447',
    success: '#8EDD9C',
    successContainer: '#005321',
    onSuccessContainer: '#A9F5B6',
    warning: '#FABD00',
    warningContainer: '#5B4300',
    onWarningContainer: '#FFDF9E',
  },
} as const;

export type M3Scheme = { [K in keyof typeof m3.light]: string };

export function getScheme(dark: boolean): M3Scheme {
  return (dark ? m3.dark : m3.light) as M3Scheme;
}

/** React Native Paper MD3 themes wired to the same palette. */
export const paperLightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: m3.light.primary,
    onPrimary: m3.light.onPrimary,
    primaryContainer: m3.light.primaryContainer,
    onPrimaryContainer: m3.light.onPrimaryContainer,
    secondary: m3.light.secondary,
    secondaryContainer: m3.light.secondaryContainer,
    onSecondaryContainer: m3.light.onSecondaryContainer,
    tertiary: m3.light.tertiary,
    tertiaryContainer: m3.light.tertiaryContainer,
    error: m3.light.error,
    errorContainer: m3.light.errorContainer,
    onErrorContainer: m3.light.onErrorContainer,
    background: m3.light.surface,
    surface: m3.light.surface,
    surfaceVariant: m3.light.surfaceVariant,
    onSurface: m3.light.onSurface,
    onSurfaceVariant: m3.light.onSurfaceVariant,
    outline: m3.light.outline,
    outlineVariant: m3.light.outlineVariant,
    inverseSurface: m3.light.inverseSurface,
    inverseOnSurface: m3.light.inverseOnSurface,
    inversePrimary: m3.light.inversePrimary,
  },
};

export const paperDarkTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: m3.dark.primary,
    onPrimary: m3.dark.onPrimary,
    primaryContainer: m3.dark.primaryContainer,
    onPrimaryContainer: m3.dark.onPrimaryContainer,
    secondary: m3.dark.secondary,
    secondaryContainer: m3.dark.secondaryContainer,
    onSecondaryContainer: m3.dark.onSecondaryContainer,
    tertiary: m3.dark.tertiary,
    tertiaryContainer: m3.dark.tertiaryContainer,
    error: m3.dark.error,
    errorContainer: m3.dark.errorContainer,
    onErrorContainer: m3.dark.onErrorContainer,
    background: m3.dark.surface,
    surface: m3.dark.surface,
    surfaceVariant: m3.dark.surfaceVariant,
    onSurface: m3.dark.onSurface,
    onSurfaceVariant: m3.dark.onSurfaceVariant,
    outline: m3.dark.outline,
    outlineVariant: m3.dark.outlineVariant,
    inverseSurface: m3.dark.inverseSurface,
    inverseOnSurface: m3.dark.inverseOnSurface,
    inversePrimary: m3.dark.inversePrimary,
  },
};
