/**
 * Domain enums shared by API, admin dashboard, and (Phase 2) mobile app.
 * These are the canonical string values persisted in MongoDB — never rename
 * a member without a data migration.
 */

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum CommunityType {
  VILLAGE = 'VILLAGE',
  APARTMENT = 'APARTMENT',
  SOCIETY = 'SOCIETY',
  CLUB = 'CLUB',
  TEMPLE = 'TEMPLE',
  INSTITUTION = 'INSTITUTION',
  TRUST = 'TRUST',
}

export enum CommunityStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum PaymentType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  EVENT_CONTRIBUTION = 'EVENT_CONTRIBUTION',
  DONATION = 'DONATION',
  SPONSORSHIP = 'SPONSORSHIP',
  MISC = 'MISC',
}

export enum PaymentMethod {
  RAZORPAY = 'RAZORPAY',
  CASH = 'CASH',
  UPI = 'UPI',
}

export enum PaymentStatus {
  PAID = 'PAID',
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  OVERDUE = 'OVERDUE',
}

export enum SubscriptionStatus {
  CREATED = 'CREATED',
  AUTHENTICATED = 'AUTHENTICATED',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  HALTED = 'HALTED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum EventFundingMode {
  /** Paid from the community's available balance — no member contributions. */
  BALANCE = 'BALANCE',
  /** Budget split equally among the selected (or all) active members. */
  SPLIT = 'SPLIT',
}

export enum EventCategory {
  TEMPLE_FESTIVAL = 'TEMPLE_FESTIVAL',
  SPORTS = 'SPORTS',
  ANNUAL_MEETING = 'ANNUAL_MEETING',
  CHARITY = 'CHARITY',
  EMERGENCY_COLLECTION = 'EMERGENCY_COLLECTION',
  OTHER = 'OTHER',
}

export enum ExpenseStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum IncomeSource {
  SUBSCRIPTION = 'SUBSCRIPTION',
  DONATION = 'DONATION',
  SPONSORSHIP = 'SPONSORSHIP',
  TEMPLE = 'TEMPLE',
  EVENT = 'EVENT',
  MISC = 'MISC',
}

export enum DocumentType {
  BILL = 'BILL',
  RECEIPT = 'RECEIPT',
  INVOICE = 'INVOICE',
  EVENT_PHOTO = 'EVENT_PHOTO',
  PROFILE_IMAGE = 'PROFILE_IMAGE',
  COMMUNITY_LOGO = 'COMMUNITY_LOGO',
  OTHER = 'OTHER',
}

export enum NotificationType {
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  BUDGET_UPDATED = 'BUDGET_UPDATED',
  REPORT_READY = 'REPORT_READY',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  EMERGENCY = 'EMERGENCY',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SUSPEND = 'SUSPEND',
  ACTIVATE = 'ACTIVATE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUND = 'REFUND',
  SUBSCRIPTION_CHANGED = 'SUBSCRIPTION_CHANGED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  REPORT_EXPORTED = 'REPORT_EXPORTED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  PERIOD_CLOSED = 'PERIOD_CLOSED',
  PASSWORD_RESET = 'PASSWORD_RESET',
}

export enum AuditEntity {
  USER = 'USER',
  COMMUNITY = 'COMMUNITY',
  EVENT = 'EVENT',
  EXPENSE = 'EXPENSE',
  INCOME = 'INCOME',
  PAYMENT = 'PAYMENT',
  SUBSCRIPTION = 'SUBSCRIPTION',
  DOCUMENT = 'DOCUMENT',
  SETTINGS = 'SETTINGS',
  REPORT = 'REPORT',
  NOTIFICATION = 'NOTIFICATION',
  FEE_CONFIG = 'FEE_CONFIG',
  ADJUSTMENT = 'ADJUSTMENT',
  SESSION = 'SESSION',
}

export enum ReportPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
}

export enum ExportFormat {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
}
